name: Python Mechanic Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  python-mechanic-checks:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install vulture mypy snakefood pytest pytest-cov
    
    - name: Run Dead Code Analysis
      run: |
        python -m vulture python-agent/ --exclude "*.js,*.ts,*.json" --min-confidence 60
        echo "Dead code analysis completed"
    
    - name: Run Type Checking
      run: |
        python -m mypy python-agent/ --strict --ignore-missing-imports || true
        echo "Type checking completed"
    
    - name: Run Import Analysis
      run: |
        python tools/python-mechanic/codemods/fix_missing_exports.py
        echo "Import analysis completed"
    
    - name: Run Runtime Probe
      run: |
        python tools/python-mechanic/runtime_probe.py
        echo "Runtime probe completed"
    
    - name: Run Repro Tests
      run: |
        python -m pytest tests/repro/ -v
        echo "Repro tests completed"
    
    - name: Generate Reports
      run: |
        mkdir -p reports
        echo "Python Mechanic Report" > reports/summary.txt
        echo "Generated: $(date)" >> reports/summary.txt
        echo "Python Version: ${{ matrix.python-version }}" >> reports/summary.txt
        echo "Status: Checks completed" >> reports/summary.txt
    
    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
        name: python-mechanic-reports-${{ matrix.python-version }}
        path: reports/
